### ISSUE TITLE
Jumping Pointer/Display Radial Gauge

### ISSUE THREAD

**Issue by DerTom1978** [mxtommy/Kip#179]
Hi,

The pointer of the Radial Gauge jumps back and forth from 0 to the correct value.
The numerical value underneath seems to stay at the correct value.
How can I prevent the pointer from jumping?

I have uploaded a video. This shows the problem

BR Tom

https://user-images.githubusercontent.com/51379696/230718738-04ba20b9-f5b1-4886-885b-6f8aaf15b757.mp4

**Comment by DerTom1978** [comment]
i also tried this later with another PC and with another browser.
The result is unfortunately always the same.
The indicator jumps back and forth.

**Comment by JonyIvy** [comment]
Same problem here with my SOG gauge.

**Comment by godind** [comment]
@DerTom1978 @JonyIvy can you explain how I could repeat the problem? I can recreate it.

Maybe share the following gauge config details:
Display

- Min Integer and Decimal places
- Min and Max value

Path

- Signal K Path
- Data Source
- Display Format

Setting option

**Comment by godind** [comment]
@JonyIvy  @DerTom1978 Can you also please check the KIP Data Browser to see if that data jumps. Filter on the path you are using:

- check the value with the default unit, then try changing to another unit by clicking the units button. Maybe the problem is in the units conversion and not the gauge it's self...?

**Comment by godind** [comment]
I think I fixed it in v2 - next release. linear and radial gauge should also be smoother.
