### ISSUE TITLE
Connects to /signalk/v1/stream but doesnt use websocket

### ISSUE THREAD

**Issue by rob42** [mxtommy/Kip#20]
Seems to switch to ws, then fail on each call. I remember you said it was polling rather than ws?

In that case it should use /signalk/v1/api or some long-polling scheme. Happy to help work it out as the artemis server should transparently handle ws, long-polling, comet, etc but doesnt in this case.

**Comment by mxtommy** [comment]
Do you know exactly what is failing?

The flow is the following:

1) Connect to the API Url given in the config (the main api that gives server version and available endpoints, usually available at /signalk. if the URL given does not contain "/signalk" it tries adding it automatically.

Following two happen asynchronously (so at same time more or less)
2a) Fetch the full signalK tree from the rest http api url learned in step 1.
2b) Connect to WS and start receiving deltas.

I do 2a to fetch stuff that doesn't change (draft/vessel name/etc) so stuff that you wouldn't get a delta. Note that since I wrote it I think sbender changed the behavior so that upon connection to WS you get a delta for all current values, negating the need to do 2a. It doens't hurt anything though.

Currently it only scrapes the REST http endpoint once upon connection. The rest should come via WS. Note I've not tried the java version of the server. It's possible it's sending something in the delta's that's causing KIP to not like the deltas? (is there a public java server I can test against?)

Note I'm leaving for 2 weeks vacation on the boat tomorrow, so please be patient :)
