### ISSUE TITLE
[object Object] error message

### ISSUE THREAD

**Issue by tkurki** [mxtommy/Kip#271]
Navigating to settings shows me this

<img width="491" alt="image" src="https://github.com/mxtommy/Kip/assets/1049678/4fae7639-a3f6-4f81-8050-0d983d92f7ef">

and does not really tell the end user anything useful. So maybe worth just removing that error message?

**Comment by godind** [comment]
How did you get to this error? Just a plain install and going to settings?

**Comment by tkurki** [comment]
Yes.

**Comment by godind** [comment]
I tried to reproduce with no luck:
1. from clean install and simply going to: Configuration / Setting / Storage
2. from clean install, adding the connection to the server, and simply going to: Configuration / Setting / Storage 
3. from clean install, adding the connection with user authentication to the server, and simply going to: Configuration / Setting / Storage

Can you share setup detail and reproduction steps? I see from the Error message you shared that it's related to remote storage / configuration storage.

- What SK permission level does you user have?
- Do you have any files in: applicationData/users/<user>/kip ?
- Do you have any files in: applicationData/global//kip ? 

Thanks

**Comment by tkurki** [comment]
- nothing in applicationData
- cleared browser localStorage
- load Kip
- configure server url
- unlock layout, add one numeric display, lock layout
- select Configuration - Settings

**Comment by godind** [comment]
You are not authenticating to SK. Just connection with a URL, right?

**Comment by tkurki** [comment]
Security on the server is off.

**Comment by godind** [comment]
You mean all options are off? Like so?
![image](https://github.com/mxtommy/Kip/assets/34038713/45a50e52-d0a8-4d98-8502-d2c3f07db53f)

Disabling `Allow Readonly Access`  does give me the same error. It's caused by an Application Data Storage Interface call that fails since Readonly is off and you are not authenticated.

KIP requires either `Allow Readonly Access` or authenticating with a user, and `Application Data Storage` Interface to be enabled. Is there a way to check these setting using some remote API call?

**Comment by tkurki** [comment]
No, I mean server's *security* mechanism is *OFF*: it has not been enabled. There is no login in the admin ui top right and trying to access security settings gives you the `Enable security`screen.
