### ISSUE TITLE
Feature Request: Add ability to save default config on server.

### ISSUE THREAD

**Issue by NAHANNIV** [mxtommy/Kip#30]
I think it would be useful if you could have a way to store a default configuration on the server.
Then each new device would not have to set everything up from a blank page.
Especially useful when the configurations become complex.

**Comment by mxtommy** [comment]
Indeed this would be useful. I think they had started a server plugin to store data, not sure what happened with it. I'll try and find some time. :)

**Comment by skipperearly** [comment]
How about extending the "save" function in the config tab with a "save as" and "Load" to the localhost, basically doing the cut/paste for the user with a text file on the server. 
Just my 2 cent.

**Comment by Jamos1988** [comment]
Looking for this feature as well, I am running on multiple devices / browsers potentially, would be a great feature! So, +1 here!

**Comment by mxtommy** [comment]
Done in da21dcda240683d6a1360b31775d4f861cfd402e ! Will try and push new version to NPM soon!

Note requires Node server version 1.27.0 or greater

It doesn't load a saved config by default, but not much work to load it. 

To save to server you also need to have a R/W Token. Request it in settings under Signal K, then you have to approve it in the Node server admin page. In order to save to global scope (to use in other places) you also have to set that device to Admin permissions in Security. The user scope is limited to the token you are using.

**Comment by VibroAxe** [comment]
@mxtommy It would be really useful if kip could load a "default" config (perhaps one named "default" if it exists) in addition to this save / load. As you say above, not a huge ammount of work for the user, but more complexity than required I feel. Would you feel this would be a new FR or a reopen of an old?
