### ISSUE TITLE
feature: Add Localtime

### ISSUE THREAD

**Issue by oyve** [mxtommy/Kip#94]
Thanks for a great plugin!

Would love to see the possibility to set a default value for NULL values, i.e. to display a message when there is nothing to display in a textbox.

**Comment by mxtommy** [comment]
I feel like this would be better handled on the server side? Kip displays whatever it gets from the server. What is your specific use case? 

Thanks

**Comment by davidsanner** [comment]
fyi, a PR for nmea0183-signalk RMC decoder was just merged which now returns NULL for empty values such as lat/lon/sog/cog/variation (instead of incorrectly returning a zero or -1).  It's a start as many of these sentences return zero or empty string for missing data instead of null as per the specification.
I was just looking into storing localtime on the server and some think that the server should hold only UTC and clients should do the calculation for localtime (or any tz eg. signalk/instrumentpanel).  Might localtime be added to KIP?  Under settings or units? (btw, great plugin, well done all around, thanks)

**Comment by godind** [comment]
A new Date value Widget will be released in V2 allowing you to set timezone and date/time format. To be released soon! Have fun!
